### ISSUE TITLE
Add isEvent!T and EventType for generic code

### ISSUE THREAD

**Issue by jpf91** [WebFreak001/EventSystem#1]
For generic code a `isEvent` would be nice. I use this for now:
```d
enum bool isEvent(T) = isArray!T && isDelegate!(ElementType!T) &&
    (is(ReturnType!(ElementType!T) == bool) || is(ReturnType!(ElementType!T) == void));
```

Usage:
```d
foreach (member; __traits(derivedMembers, API))
{
    static if(isEvent!(typeof(__traits(getMember, API, member))))
    {
        registerEvent!member;
    }
}

void registerEvent(string name)()
{
    alias EventType = ElementType!(typeof(__traits(getMember, API, name)));
    alias TRet = ReturnType!EventType;
    alias TArgs = Parameters!EventType;

    TRet onEvent(TArgs args)
    {
        //...

        static if(is(TRet == bool))
            return true;
    }

    mixin(`_api.` ~ name ~` ~= &onEvent;`);
}
```

**Comment by WebFreak001** [comment]
Made it so it works with types & variables + different one for event & cancelable and one that returns true for both (isEmittable). It still doesn't import anything and just uses the `is` expression

**Comment by jpf91** [comment]
Thanks. Unfortunately I can't use this as a drop-in replacement for the implementation posted above as this causes errors for invalid types:

```d
../../../.dub/packages/eventsystem-1.2.0/eventsystem/source/tinyevent.d(31,28): Error: function does not have a default initializer
src/vibe/rpcchannel/base.d(57,42): Error: template instance tinyevent.isEmittable!(void(string, int)) error instantiating
```

I need these templates to select events from `__traits(allMembers)` so I'll end up passing all kinds of non-event types to these templates. Unfortunately even short-circuiting like this doesn't work: `isEmittable2(T) = !isSomeFunction!T && isEmittable!T;`.

Another useful function is `EventCallType` which simply returns `typeof(Event.init[0])`.

**Comment by WebFreak001** [comment]
uh try adding a __traits(compiles, ...)
